---
- hosts: all
  remote_user: root
  #remote_user: root
  #become: yes
  #become_method: sudo

  tasks:
    #- name: upgrade all packages
     #apt:
       #name: '*'
       #state: latest

   - name: upgrade all packages
     package:
       name: "*"
       state: latest
